server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: highSchool
  config:
    import: key.yaml
  datasource:
    url: ${key.datasource.url}
    username: ${key.datasource.username}
    password: ${key.datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false